project_id = "mrjszsjqnpzjamczddzd"

[functions.generate-product-image]
verify_jwt = false

[functions.upload-generated-images]
verify_jwt = false

[functions.generate-and-upload-all-images]
verify_jwt = false

[functions.upload-generated-images-final]
verify_jwt = false

[functions.upload-all-product-images]
verify_jwt = false