name: Vite + Capacitor → APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assert android dir exists (fail fast)
        run: |
          test -d android || (echo "ERROR: android/ no existe" && exit 1)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      # IMPORTANTE: primero Android SDK…
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # …después Java 21 (para que no nos pisen JAVA_HOME)
      - id: jdk
        name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Check Java versions
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          javac -version

      # Forzar a Gradle a usar este JAVA_HOME=21
      - name: Pin JAVA_HOME 21 into gradle.properties
        run: |
          echo "org.gradle.java.home=${JAVA_HOME}" >> android/gradle.properties
          echo "Wrote org.gradle.java.home to android/gradle.properties"

      - name: Sync Capacitor
        run: |
          npx cap copy android
          npx cap sync android

      - name: Build Release APK
        working-directory: android
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}  # redundante, pero explícito
        run: |
          chmod +x gradlew
          ./gradlew --version
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/release/app-release-unsigned.apk
