name: Vite + Capacitor → APK
on: { push: { branches: [ "main" ] }, pull_request: { branches: [ "main" ] } }
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v4

      - name: Assert android dir exists (fail fast)
        run: |
          ls -la
          test -d android || (echo "ERROR: android/ no existe en el repo" && exit 1)
          ls -la android

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Check Java
        run: |
          java -version
          javac -version
      - name: Check Java
        run: |
          java -version
          javac -version
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Sync Capacitor (usa android/ del repo)
=======
      - uses: actions/checkout@v4
      - name: Assert android dir exists
        run: test -d android || (echo "ERROR: android/ no existe" && exit 1)
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - name: Install deps
        run: npm ci
      - name: Build web (Vite)
        run: npm run build
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '21', cache: gradle }
      - uses: android-actions/setup-android@v3
      - name: Sync Capacitor
>>>>>>> chore(android): ensure Capacitor android & CI (Java 21) + sync
        run: |
          npx cap copy android
          npx cap sync android
      - name: Build Release APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon
<<<<<<< HEAD

      - name: Upload APK
        uses: actions/upload-artifact@v4
=======
      - uses: actions/upload-artifact@v4
>>>>>>> chore(android): ensure Capacitor android & CI (Java 21) + sync
        with:
          name: app-release-apk
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/release/app-release-unsigned.apk
