name: Vite + Capacitor → APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Ensure Capacitor Android
        run: npm i @capacitor/android

      - name: Build web (Vite)
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Capacitor init (idempotent)
        run: npx cap init "Casa Beatricita" "com.casabeatricita.app" --web-dir=dist || true

      - name: Add & Sync Android
        run: |
          npx cap add android || true
          npx cap copy android
          npx cap sync android

      - name: Build Release APK
        working-directory: android
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
