name: Build iOS IPA (Capacitor, unsigned)

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: "Bundle ID iOS (reverse-DNS)"
        required: true
        default: "com.casabeatricita.app"
      app_name:
        description: "Nombre de la app"
        required: true
        default: "Casa Beatricita"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web (Vite)
        run: npm run build

      - name: Add Capacitor (runtime-only, no repo changes)
        run: |
          npm i @capacitor/core @capacitor/cli
          npm i -D @capacitor/ios
          cat > capacitor.config.ts <<'EOF'
          import type { CapacitorConfig } from '@capacitor/cli';
          const config: CapacitorConfig = {
            appId: '${{ github.event.inputs.app_id }}',
            appName: '${{ github.event.inputs.app_name }}',
            webDir: 'dist',
            bundledWebRuntime: false
          };
          export default config;
          EOF

      - name: Generate iOS project & sync (pods)
        run: |
          npx cap add ios
          npx cap sync ios

      - name: Build .app (unsigned)
        working-directory: ios
        run: |
          xcodebuild \
            -workspace App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_IDENTITY="" \
            clean build

      - name: Package IPA (unsigned)
        run: |
          mkdir -p Payload
          APP_PATH=$(find ios -path "*Release-iphoneos/*.app" -type d | head -n 1)
          cp -R "$APP_PATH" Payload/
          zip -r app-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: app-unsigned.ipa
          retention-days: 7
